version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    deploy:
      replicas: 2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
